// Kotlin runner for the Web Bot Auth profile corpus (webbotauth_v0).
//
// Independently reproduces every verdict in the frozen corpus. The PROFILE rules
// (signing base, coverage completeness, freshness window, directory keyid
// resolution, Signature-Agent SSRF, Ed25519 verification) are re-implemented here
// from the corpus `policy` block, NOT imported from the generator's oracle, so a
// runner passing is genuine agreement rather than an echo. This mirrors the Python
// reference runner (runners/python/verify_wba.py) and the go/typescript runners
// case for case.
//
// Self-contained, mirroring the sibling runners/kotlin/NegativeV1.kt: JSON via
// Jackson (com.fasterxml.jackson.databind) and Ed25519 via Bouncy Castle, the
// exact jars tools/run_consensus_wba.sh puts on the classpath (runners/kotlin/libs/*.jar).
// It is compiled and run identically to the sibling:
//     kotlinc VerifyWba.kt -cp "$JAR" -include-runtime -d verifywba.jar
//     java -cp "verifywba.jar:$JAR" VerifyWbaKt <corpus.json>
//
// Corpus path: argv[0], else the sibling repo default. Exit 0 iff every case matches.

import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.ObjectMapper
import org.bouncycastle.crypto.params.Ed25519PublicKeyParameters
import org.bouncycastle.crypto.signers.Ed25519Signer
import java.io.File
import java.net.URI
import java.util.Base64
import kotlin.system.exitProcess

private const val DEFAULT_PATH = "../../corpus/webbotauth_v0/webbotauth_v0.json"

private class SigningBaseError(m: String) : RuntimeException(m)

// ---- generic helpers -------------------------------------------------------

// Standard base64 decode tolerant of missing padding (the corpus is generated by
// python base64.b64encode, i.e. padded standard base64; the pad-repair keeps the
// decode robust either way). Returns the raw bytes.
private fun b64(s: String): ByteArray {
    val pad = (4 - s.length % 4) % 4
    return Base64.getDecoder().decode(s + "=".repeat(pad))
}

private fun hex(s: String): ByteArray {
    val out = ByteArray(s.length / 2)
    for (i in s.indices step 2) out[i / 2] = s.substring(i, i + 2).toInt(16).toByte()
    return out
}

private fun noteOf(c: JsonNode): String = if (c.hasNonNull("note")) c.get("note").asText() else ""

// ---- Rule 1: RFC 9421 Section 2.5 signing base, by direct concatenation -----
// @authority/@method/@path come from the top-level fields; any other component is
// a header looked up (lowercased) in `headers`. A missing covered value makes the
// base unbuildable (throws), which the driver maps to a negative verdict.
private fun strField(input: JsonNode, field: String): String {
    val n = input.get(field)
    if (n == null || n.isNull) throw SigningBaseError("$field covered but not supplied")
    return n.asText()
}

private fun buildSigningBase(input: JsonNode, paramsRaw: String?): String {
    val headers = input.get("headers")
    val lines = ArrayList<String>()
    for (compNode in input.get("covered_components")) {
        val name = compNode.asText().lowercase()
        val value: String = when (name) {
            "@authority" -> strField(input, "authority")
            "@method" -> strField(input, "method")
            "@path" -> strField(input, "path")
            else -> {
                val hv = if (headers != null && headers.isObject) headers.get(name) else null
                if (hv == null || hv.isNull) throw SigningBaseError("covered header $name not present")
                hv.asText()
            }
        }
        lines.add("\"$name\": $value")
    }
    lines.add("\"@signature-params\": ${paramsRaw ?: ""}")
    return lines.joinToString("\n")
}

// ---- Rule 2: coverage completeness (required lowercased subset of covered) ---
private fun coverageOk(covered: JsonNode?, required: List<String>): Boolean {
    val have = HashSet<String>()
    covered?.forEach { have.add(it.asText().lowercase()) }
    return required.all { have.contains(it.lowercase()) }
}

// ---- Rule 3: freshness window -----------------------------------------------
// All three must be integers (mirrors Python isinstance(x, int); a JSON float is
// rejected), expires > created, and (created - skew) <= now < expires.
private fun freshnessOk(c: JsonNode, skew: Long): Boolean {
    val cr = c.get("created"); val ex = c.get("expires"); val nw = c.get("now")
    if (cr == null || ex == null || nw == null) return false
    if (!cr.isIntegralNumber || !ex.isIntegralNumber || !nw.isIntegralNumber) return false
    val created = cr.asLong(); val expires = ex.asLong(); val now = nw.asLong()
    if (expires <= created) return false
    return (created - skew) <= now && now < expires
}

// ---- Rule 4: directory keyid resolution to a usable Ed25519 JWK -------------
private fun directoryOk(directory: JsonNode?, keyid: String): Boolean {
    if (directory == null) return false
    for (j in directory) {
        val kid = if (j.hasNonNull("kid")) j.get("kid").asText() else null
        if (kid == keyid) {
            val kty = if (j.hasNonNull("kty")) j.get("kty").asText() else null
            val crv = if (j.hasNonNull("crv")) j.get("crv").asText() else null
            val x = if (j.hasNonNull("x")) j.get("x").asText() else null
            return kty == "OKP" && crv == "Ed25519" && !x.isNullOrEmpty()
        }
    }
    return false
}

// ---- Rule 5: Signature-Agent SSRF guard -------------------------------------
// https required; userinfo rejected; host IP-literal (v4 or [v6]) else the
// resolved IP; reject if the address is inside ANY denied CIDR of the SAME IP
// version. IP literals are parsed to raw bytes (no DNS, no IPv4-mapped collapse)
// and CIDR membership is by byte prefix-mask, matching Python's ipaddress.
private fun parseIpv4(s: String): ByteArray? {
    val parts = s.split(".")
    if (parts.size != 4) return null
    val out = ByteArray(4)
    for (i in 0..3) {
        val p = parts[i]
        if (p.isEmpty() || p.length > 3 || !p.all { it in '0'..'9' }) return null
        if (p.length > 1 && p[0] == '0') return null // reject leading zeros (py3.9+ strict)
        val n = p.toInt()
        if (n > 255) return null
        out[i] = n.toByte()
    }
    return out
}

private fun groupsOf(part: String): List<Int>? {
    if (part.isEmpty()) return emptyList()
    val segs = part.split(":")
    val out = ArrayList<Int>()
    for (k in segs.indices) {
        val seg = segs[k]
        if (seg.contains(".")) {
            if (k != segs.size - 1) return null // embedded IPv4 must be last
            val v4 = parseIpv4(seg) ?: return null
            out.add(((v4[0].toInt() and 0xFF) shl 8) or (v4[1].toInt() and 0xFF))
            out.add(((v4[2].toInt() and 0xFF) shl 8) or (v4[3].toInt() and 0xFF))
        } else {
            if (!Regex("^[0-9a-fA-F]{1,4}$").matches(seg)) return null
            out.add(seg.toInt(16))
        }
    }
    return out
}

private fun parseIpv6(s: String): ByteArray? {
    if (s.isEmpty()) return null
    if (Regex("::").findAll(s).count() > 1) return null // at most one "::"
    val groups: List<Int>
    if (s.contains("::")) {
        val idx = s.indexOf("::")
        val head = groupsOf(s.substring(0, idx)) ?: return null
        val tail = groupsOf(s.substring(idx + 2)) ?: return null
        val missing = 8 - head.size - tail.size
        if (missing < 1) return null // "::" must stand for at least one group
        groups = head + List(missing) { 0 } + tail
    } else {
        groups = groupsOf(s) ?: return null
    }
    if (groups.size != 8) return null
    val out = ByteArray(16)
    for (i in 0..7) {
        val g = groups[i]
        if (g < 0 || g > 0xFFFF) return null
        out[2 * i] = ((g ushr 8) and 0xFF).toByte()
        out[2 * i + 1] = (g and 0xFF).toByte()
    }
    return out
}

private fun parseIpLiteral(s: String): ByteArray? {
    parseIpv4(s)?.let { return it }
    return parseIpv6(s)
}

private fun inCidr(addr: ByteArray, net: ByteArray, prefix: Int): Boolean {
    if (addr.size != net.size) return false
    if (prefix < 0 || prefix > addr.size * 8) return false
    var bits = prefix
    for (i in addr.indices) {
        if (bits <= 0) break
        val take = if (bits >= 8) 8 else bits
        val mask = (0xFF shl (8 - take)) and 0xFF
        if ((addr[i].toInt() and mask) != (net[i].toInt() and mask)) return false
        bits -= 8
    }
    return true
}

private fun ssrfOk(url: String, resolvedIp: String?, requireHttps: Boolean, deniedCidrs: List<String>): Boolean {
    val uri = try { URI(url) } catch (e: Exception) { return false }
    val scheme = uri.scheme?.lowercase()
    if (requireHttps && scheme != "https") return false
    if (uri.rawUserInfo != null) return false // userinfo ("user@host") -> reject
    val rawHost = uri.host ?: return false
    if (rawHost.isEmpty()) return false
    val host = rawHost.trim('[', ']') // strip IPv6 brackets
    var addr = parseIpLiteral(host)
    if (addr == null) {
        // hostname is a domain -> rely on the resolved address
        if (resolvedIp.isNullOrEmpty()) return false
        addr = parseIpLiteral(resolvedIp) ?: return false
    }
    for (cidr in deniedCidrs) {
        val slash = cidr.lastIndexOf('/')
        if (slash < 0) continue
        val net = parseIpLiteral(cidr.substring(0, slash)) ?: continue
        val prefix = cidr.substring(slash + 1).toIntOrNull() ?: continue
        // Same IP version only, mirroring the Python reference.
        if (net.size == addr.size && inCidr(addr, net, prefix)) return false
    }
    return true
}

// ---- Rule 6: Ed25519 verify of the raw signing-base bytes -------------------
private fun ed25519Ok(msg: ByteArray, sigHex: String, pkHex: String): Boolean {
    return try {
        val pk = hex(pkHex)
        if (pk.size != 32) return false
        val sig = hex(sigHex)
        if (sig.size != 64) return false
        val signer = Ed25519Signer()
        signer.init(false, Ed25519PublicKeyParameters(pk, 0))
        signer.update(msg, 0, msg.size)
        signer.verifySignature(sig)
    } catch (e: Exception) {
        false
    }
}

// ---- driver ----------------------------------------------------------------
fun main(args: Array<String>) {
    val path = if (args.isNotEmpty()) args[0] else DEFAULT_PATH
    val corpus = ObjectMapper().readTree(File(path))

    val policy = corpus.get("policy")
    val required = ArrayList<String>()
    policy.get("required_covered_components")?.forEach { required.add(it.asText()) }
    val skew = policy.get("clock_skew_seconds")?.let { if (it.isIntegralNumber) it.asLong() else 0L } ?: 0L
    val ssrf = policy.get("ssrf")
    val requireHttps = ssrf?.get("require_https")?.let { if (it.isBoolean) it.asBoolean() else true } ?: true
    val deniedCidrs = ArrayList<String>()
    ssrf?.get("denied_cidrs")?.forEach { deniedCidrs.add(it.asText()) }

    var total = 0; var matched = 0
    val fails = ArrayList<String>()
    fun record(ok: Boolean, section: String, note: String) {
        total++
        if (ok) matched++ else fails.add("[$section] $note")
    }

    // 1. wba_signing_base
    for (c in corpus.get("wba_signing_base")) {
        val want = String(b64(c.get("signing_base_b64").asText()), Charsets.UTF_8)
        val spr = if (c.hasNonNull("signature_params_raw")) c.get("signature_params_raw").asText() else null
        val okFlag = c.get("ok").asBoolean()
        // Build FIRST; `okFlag && build(...)` would short-circuit for negative
        // cases and never exercise the build-failure path.
        val ok = try {
            val built = buildSigningBase(c.get("in"), spr)
            okFlag && built == want
        } catch (e: SigningBaseError) {
            !okFlag
        }
        record(ok, "wba_signing_base", noteOf(c))
    }

    // 2. wba_coverage
    for (c in corpus.get("wba_coverage")) {
        val got = coverageOk(c.get("covered_components"), required)
        record(got == c.get("expect_accept").asBoolean(), "wba_coverage", noteOf(c))
    }

    // 3. wba_freshness
    for (c in corpus.get("wba_freshness")) {
        val got = freshnessOk(c, skew)
        record(got == c.get("expect_accept").asBoolean(), "wba_freshness", noteOf(c))
    }

    // 4. wba_directory
    for (c in corpus.get("wba_directory")) {
        val got = directoryOk(c.get("directory"), c.get("keyid").asText())
        record(got == c.get("expect_accept").asBoolean(), "wba_directory", noteOf(c))
    }

    // 5. wba_directory_ssrf
    for (c in corpus.get("wba_directory_ssrf")) {
        val resolved = if (c.hasNonNull("resolved_ip")) c.get("resolved_ip").asText() else null
        val got = ssrfOk(c.get("signature_agent_url").asText(), resolved, requireHttps, deniedCidrs)
        record(got == c.get("expect_fetch_allowed").asBoolean(), "wba_directory_ssrf", noteOf(c))
    }

    // 6. wba_ed25519_verify
    for (c in corpus.get("wba_ed25519_verify")) {
        val msg = b64(c.get("signing_base_b64").asText())
        val valid = ed25519Ok(msg, c.get("sig_hex").asText(), c.get("pk_hex").asText())
        record(valid == c.get("expect_valid").asBoolean(), "wba_ed25519_verify", noteOf(c))
    }

    fails.forEach { println("FAIL  $it") }
    println("\nkotlin (wba): $matched/$total cases matched")
    exitProcess(if (matched == total) 0 else 1)
}
